### ISSUE TITLE
Add Language throws exception

### ISSUE THREAD

**Issue by hermitdave** [TechnikEmpire/language-detection#1]
When using the package, a call to AddLanguage throws exception.

This does not happen with nuget package from initial port. Just thought I'd let you know.

**Comment by TechnikEmpire** [comment]
@hermitdave Can you copy the exception and stack trace into this ticket please? Thanks for reporting.

**Comment by hermitdave** [comment]
Exception details:
Message: Value cannot be null. Parameter name: stream
StackTrace:
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at LanguageDetection.LanguageDetector.AddLanguages(String[] languages)

**Comment by hempels** [comment]
I can +1 this issue. This library does not work since you can't initialize the languages.

**Comment by diegosasw** [comment]
Is this project abandoned?

**Comment by TechnikEmpire** [comment]
Yep. This science has advanced by leaps and bounds. I'd recommend looking at deep models and use OnnxRuntime for inference.
