### ISSUE TITLE
Question : Turkish content detection

### ISSUE THREAD

**Issue by HakanKaraoglu** [TechnikEmpire/language-detection#4]
Hello,
We have an old java project and it uses shuyo's language perception library. Meanwhile, we're converting the java project to .net.

It can perceive the Turkish content I provided in the Java project as "tr". However, this library we use on the .net side does not give the same result. What could be the problem, or what configuration should we do?

Turkish Content : "**24 kasım wall post test**"

**Comment by TechnikEmpire** [comment]
I'm not sure. This project is a fork of another project and I dont use this anymore. I have my own content filtering software in 44 languages so unfortunately I can't offer any advice on an alternative because that's proprietary. 

All the best.
